print("Welcome to the Tip Calculator")
b = input("What was the total bill? ")
t = input("what percentage tip would you like to give? 10, 12 or 15? ")
p = input("How many people to split the bill? ")
b1 = float(b)
t1 = int(t)
p1 = int(p)
c = ((b1 + (b1*(t1/100)))/p1)
c1 = float(c)
c2 = round (c1, 2)
print(f"Each person should pay: $ {c2}")
